---
title: "Blog post"
author: "Taras Kaduk"
date: "February 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This post kicks off not one, but two series of posts and two projects at the same time! 

# Intro
I love being on the move. To me, the best way to experience a new country or a new city is to live there. There are a few cities in the world that can serve as your ultimate destination - think NYC, San Fran, LA, Hong Kong, London, Paris - but the vast majority of places is, in my mind, interchangeable. 

While in the US, I lived in Jacksonville, FL, then moved to Seattle, WA, and later moved back to Jacksonville. I also have got to see many other places and explore different destinations. I've learned that, like everything else in life, living anywhere is always a trade-off: how fun/boring is it, how good/bad is the weather, what are real estate prices like, what about state and local taxes, have you checked the crime rates, what's the politics like, are there any cool destinations nearby, is the local airport big enough to connect with other desired destinations, et cetera et cetera.

Thinking about *"Where should I move to next?"* or *"Should I take this job offer in this city?"*, good freaking luck objectively weighing your options! Which is why I always wanted to create something that would help look at all these factors in an unemotional, fact-based way. 

And so, I'm setting out to do just that. Over the course of the next several months, I'll be collecting the data on the United States cities with the purpose of building out an web app or an algorithm to help people (well, me first, and people later, come on: my world is very Tarasocentric) determine their next best place to live

## What cities?
As a US resident, and a recent naturalized US citizen, I will only focus on the U.S. cities for now. Factoring in places outside of US is a whole other challenge from many perspectives: there will be issues finding similar data across many countries, as well as many new data points of the country-level importance would be necessary. I'll leave it out for now. I've seen some amazing tools to determine which country fits you most: I'll let you all search Internet and perhaps find something that work for you. Finally, finding the perfect place to live anywhere in the world is nice to know, but it has little real value: can you relocate there, can you work there, do you need a visa and a permit, etc. On the contrary, moving within the US of A is really just a matter of getting up and moving: no other red tape.

## What factors?
I will start with the factors that are most important to me. Later, I'm hoping to expand this and include more ideas from people who are interested. For now, some of the things I want to look at are:
- weather: temperature, sunny days, exposure to elements and so on.
- cost of living: rent prices and real estate, city and state taxes are the major factors
- proximity to national and state parks, historic landmarks and other major cities (my family and I love roadtripping)
- traffic in and out of nearby airports (air connection to other major cities of interest)
- some state policies like gun regulations, environmental regulations
- walking, cycling and public transit scores for cities

I'm sure I'll be adding many more (and perhaps deleting a few when hitting a dead end in getting the data), but this list is a solid start.

This would be an impossible task to do on my own, and I'm looking for collaborators. I'll start a GitHub repo shortly and will keep it updated as I move along: feel free to jump in at any moment.

In fact, the connections created at this year's RStudio Conference already bring fruits: my new buddy Sage, whom I met in San Diego during the conference, has already expressed interest in participating. Looking forward to collaborating on this, man! Will the data confirm that Denver is really so great? We'll see, hahaha!

In the next blog post, I will outline my first stage, which became a project in itself: getting the weather data. Stay tuned!