---
title: "Blog post"
author: "Taras Kaduk"
date: "February 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Following up on the previous post, my first step of the project is getting the weather data for the cities in the U.S. In fact, the project itself was inspired by a blog post by Kelly Norton (@kellegous) titled ["THE PLEASANT PLACES TO LIVE"](http://kellegous.com/j/2014/02/03/pleasant-places/). https://twitter.com/kellegous/status/430466971742650368

I looked at it and thought *"Wow, can I add more components to it?"* Of course I can! But I should start by replicating this! 

Unfortunatelly, Kelly hasn't posted his methodology or his code (and if he did, it'd be in Python, I guess), and all I had to work with was the reference to the [NOAA Global Summary of the Day data archive](https://www.ncdc.noaa.gov/data-access/quick-links#gsod). Digging deeper, I found nothing but an ftp with year folders going back almost 100 years. And inside those folders? a ton of `.tar` archives (an archive per weather station)! And inside those archives? A bunch of files in a whitespace-separated format! Hoo-boy!

Since each year folders contains the daily data for all the weather stations in the world, I could proceed with one of the following things:
- I could attempt and download the data year by year, and then keep what I need.
- Or, I could figure out a way to prgramatically get the data for the weather stations I need.

I decided to go with the latter. Realizing that others may need to access the data in the future, I went on creating a process that would require more time, but could be scaled in the future. Briefly, here is what I did:
- I got the list of all the weather stations from the NOAA website. The list included each station's lat and long.
- I then reverse-geocoded the 25,000 stations using [Maëlle Salmon's](https://twitter.com/ma_salmon) `opencage` package (based on [Open Cage Geocoder](https://geocoder.opencagedata.com/))
  - with the limit of 2,500 calls a day, it took me 3 weeks to reverse geocode the entire data set (because I kept forgetting to do it daily, that's why!)
- With the supercharged list of all the weather stations, it is now only a matter of a few functions to extract only the data one needs.
- In the future, this could be made into a package. Thoughts?

In the following blog posts, I'm going to document my journey through the weather and location data. I will also take a few detours playing with this data before returning to the original purpose of getting to it in the first place: determining the best place to live!