library(drake)

library(weathermetrics)
library(tigris)
library(GSODR)
library(sp)
library(sf)
library(tidycensus)

#library(rnoaa)
# library(spData)
library(janitor)
library(scales)

# library(maps)
# library(caret)
library(gganimate)
library(lubridate)
library(stringr)
library(readxl)
library(fuzzyjoin)
library(tidyverse)